version: '3'

services:
  rabbitserver:
    build:
      context: rabbitmq
    container_name: rabbitserver
    tty: true
    ports:
      - "5671:5671"
      - "5672:5672"
      - "15672:15672"
    networks:
      - netrabbit

  receiver:
    build:
      context: receiver
    container_name: receiver
    restart: always
    links:
      - "rabbitserver:rabbitserver"
    networks:
      - netrabbit
    tty: true
    depends_on:
      - rabbitserver

  sender:
    build:
      context: sender
    container_name: sender
    links:
      - "rabbitserver:rabbitserver"
    networks:
      - netrabbit
    ports:
      - "3000:3000"
    tty: true
    depends_on:
      - rabbitserver

networks:
  netrabbit:
    driver: bridge